[build]
builder = "NIXPACKS"

[deploy]
startCommand = "sh -lc 'npm run prisma:generate && npm run migrate:deploy && node dist/main.js'"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
