[build]
builder = "NIXPACKS"

[deploy]
startCommand = "sh -lc 'npx prisma migrate deploy && npm run start:prod'"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
