[build]
builder = "NIXPACKS"

[deploy]
startCommand = "sh -lc 'ROOT=.; SCHEMA="$ROOT/prisma/schema.prisma"; npx prisma generate --schema "$SCHEMA" && npx prisma migrate deploy --schema "$SCHEMA" && node "$ROOT/dist/main.js"'"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
